version: '3'

services:
  #hugo_build:
  build:
    container_name: hugo_build
    # image: peaceiris/hugo:v0.x.x
    # image: peaceiris/hugo:v0.84.4-mod   # Hugo Modules
    # image: peaceiris/hugo:v0.84.4-full  # Hugo Modules and Node.js
    image: klakegg/hugo:0.101.0
    volumes:
      - ${PWD}:/src
    working_dir: /src
